//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomWPFnetFramework.DataBase
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class CreditCard
    {
        public System.Guid Id { get; set; }
        public string Number { get; set; }
        public string FIO { get; set; }
        public string ExpiryDate { get; set; }
        public Nullable<int> CVV { get; set; }
        [JsonIgnore]
        public byte[] PhotoPage1 { get; set; }
        [NotMapped]
        public string PhotoPage164 { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }

        [JsonIgnore]
        public virtual Item Item { get; set; }
    }
}
