//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomWPFnetFramework.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.Photo = new HashSet<Photo>();
        }
    
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public string Type { get; set; }
        public byte[] Image { get; set; }
        public int Priority { get; set; }
        public int IsHidden { get; set; }
        public int IsSelected { get; set; }
        public System.DateTime DateCreation { get; set; }
        public Nullable<System.Guid> FolderId { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual CreditCard CreditCard { get; set; }
        public virtual INN INN { get; set; }
        public virtual User User { get; set; }
        public virtual Passport Passport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Photo> Photo { get; set; }
        public virtual Polis Polis { get; set; }
        public virtual SNILS SNILS { get; set; }
        public virtual TemplateDocument TemplateDocument { get; set; }
    }
}
