//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomWPFnetFramework.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passport
    {
        public int Id { get; set; }
        public string SerialNumber { get; set; }
        public string FIO { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string BirthPlace { get; set; }
        public string ResidencePlace { get; set; }
        public string ByWhom { get; set; }
        public string DivisionCode { get; set; }
        public Nullable<System.DateTime> GiveDate { get; set; }
        public byte[] FacePhoto { get; set; }
        public byte[] PhotoPage1 { get; set; }
        public byte[] PhotoPage2 { get; set; }
    
        public virtual Items Items { get; set; }
    }
}
