//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomWPFnetFramework.DataBase
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateObject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TemplateObject()
        {
            this.TemplateDocumentData = new HashSet<TemplateDocumentData>();
        }
    
        public System.Guid Id { get; set; }
        public int Position { get; set; }
        public string Type { get; set; }
        public string Title { get; set; }
        public System.Guid TemplateId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }

        [JsonIgnore]
        public virtual Template Template { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<TemplateDocumentData> TemplateDocumentData { get; set; }
    }
}
