//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomWPFnetFramework.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateDocumentData
    {
        public int Id { get; set; }
        public string TDDValue { get; set; }
        public int TemplateObjectId { get; set; }
        public int TemplateDocumentId { get; set; }
    
        public virtual TemplateDocument TemplateDocument { get; set; }
        public virtual TemplateObject TemplateObject { get; set; }
    }
}
