//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomWPFnetFramework.DataBase
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateDocument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TemplateDocument()
        {
            this.TemplateDocumentData = new HashSet<TemplateDocumentData>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid TemplateId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }

        [JsonIgnore]
        public virtual Item Item { get; set; }
        [JsonIgnore]
        public virtual Template Template { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<TemplateDocumentData> TemplateDocumentData { get; set; }
    }
}
